In [18]:
import numpy as np
import matplotlib.pyplot as plt
plt.rcParams.update({
    "text.usetex": True,
})

In [19]:
D = [np.load("outputs/ss_run_1658771030.npz"), np.load("outputs/ss_run_1658821005.npz")]
print(list(D[0].keys()))

['α', 'ω0', 'Γ', 'dt', 'dkmax', 'epsrel', 'T', 'sss']


In [20]:
D[0]["α"], D[0]["ω0"], D[0]["Γ"]#, D["theta"]/np.pi

(array(10.), array(2.), array(1.))

In [23]:
C = np.loadtxt("charlie/MFGS_1D_x_prma_100.csv", delimiter=",", skiprows=1)
# C = np.loadtxt("charlie/MFGS_3D_xyz_prma_5.csv", delimiter=",", skiprows=1)
# C = np.loadtxt("charlie/MFGS_3D_xyz_prma_10.csv", delimiter=",", skiprows=1)
print(C.shape)

(100, 2)


In [24]:
plt.figure()
for d in D:
    plt.semilogx(d["T"], -d["sss"][:,2], '--o', color='C0')
plt.semilogx(C[:,0], -C[:,1], '-', color='C1', linewidth=2.0)
plt.tight_layout()
plt.show()
# plt.savefig("outputs/charlie_comp_1d.pdf")

---------------------

In [298]:
# D = [np.load("outputs/run_3d_T0.01_1658822870.npz"),
#      np.load("outputs/run_3d_T0.01873817422860384_1658822870.npz"),
#      np.load("outputs/run_3d_T0.03511191734215131_1658822870.npz"),
#      np.load("outputs/run_3d_T0.0657933224657568_1658822870.npz"),
#      np.load("outputs/run_3d_T0.12328467394420659_1658822870.npz"),
#      np.load("outputs/run_3d_T0.23101297000831592_1658822870.npz"),
#      np.load("outputs/run_3d_T0.4328761281083057_1658822870.npz"),
#      np.load("outputs/run_3d_T0.8111308307896868_1658822870.npz"),
#      np.load("outputs/run_3d_T1.5199110829529332_1658822870.npz")]

# D = [np.load("outputs/run_3d_T0.01_1658829742.npz"),
#      np.load("outputs/run_3d_T0.01873817422860384_1658829742.npz"),
#      np.load("outputs/run_3d_T0.03511191734215131_1658829742.npz")]

# D = [np.load(f) for f in
#      ["outputs/run_3d_T0.01_1658857049.npz",
#       "outputs/run_3d_T0.01873817422860384_1658857049.npz",
#       "outputs/run_3d_T0.03511191734215131_1658857049.npz",
#       "outputs/run_3d_T0.0657933224657568_1658857049.npz",
#       "outputs/run_3d_T0.12328467394420659_1658857049.npz",
#       "outputs/run_3d_T0.23101297000831592_1658857049.npz",
#       "outputs/run_3d_T0.4328761281083057_1658857049.npz",
#       "outputs/run_3d_T0.8111308307896868_1658857049.npz",
#       "outputs/run_3d_T1.5199110829529332_1658857049.npz"]]

# D = [np.load(f) for f in
#      ["outputs/run_3d_T0.01_1658879444.npz"]]

# D = [np.load(f) for f in
#      ["outputs/run_3d_T0.01_1658964001.npz",
#       "outputs/run_3d_T0.01873817422860384_1658964001.npz",
#       "outputs/run_3d_T0.03511191734215131_1658964001.npz",
#       "outputs/run_3d_T0.0657933224657568_1658964001.npz",
#       "outputs/run_3d_T0.12328467394420659_1658964001.npz",
#       "outputs/run_3d_T0.23101297000831592_1658964001.npz",
#       "outputs/run_3d_T0.4328761281083057_1658964001.npz",
#       "outputs/run_3d_T0.8111308307896868_1658964001.npz",
#       "outputs/run_3d_T1.5199110829529332_1658964001.npz",
#       "outputs/run_3d_T2.848035868435799_1658964001.npz"]]

# D = [np.load(f) for f in
#      ["outputs/run_3d_T0.01_1658991560.npz",
#       "outputs/run_3d_T0.01873817422860384_1658991560.npz",
#       "outputs/run_3d_T0.03511191734215131_1658991560.npz",
#       "outputs/run_3d_T0.0657933224657568_1658991560.npz",
#       "outputs/run_3d_T0.12328467394420659_1658991560.npz",
#       "outputs/run_3d_T0.23101297000831592_1658991560.npz",
#       "outputs/run_3d_T0.4328761281083057_1658991560.npz",
#       "outputs/run_3d_T0.8111308307896868_1658991560.npz",
#       "outputs/run_3d_T1.5199110829529332_1658991560.npz",
#       "outputs/run_3d_T2.848035868435799_1658991560.npz"]]

# D = [np.load(f) for f in
#      ["outputs/run_3d_T0.01_1659002443.npz",
#       "outputs/run_3d_T0.01873817422860384_1659002443.npz"]]

# D = [np.load(f) for f in
#      ["outputs/run_3d_T0.01_1659003670.npz",
#       "outputs/run_3d_T0.01873817422860384_1659003670.npz",
#       "outputs/run_3d_T0.03511191734215131_1659003670.npz",
#       "outputs/run_3d_T0.0657933224657568_1659003670.npz",
#       "outputs/run_3d_T0.12328467394420659_1659003670.npz",
#       "outputs/run_3d_T0.23101297000831592_1659003670.npz",
#       "outputs/run_3d_T0.4328761281083057_1659003670.npz"]]

# D = [np.load(f) for f in
#      ["outputs/run_3d_T0.01_1659011510.npz",
#       "outputs/run_3d_T0.01873817422860384_1659011510.npz",
#       "outputs/run_3d_T0.03511191734215131_1659011510.npz",
#       "outputs/run_3d_T0.0657933224657568_1659011510.npz",
#       "outputs/run_3d_T0.12328467394420659_1659011510.npz",
#       "outputs/run_3d_T0.23101297000831592_1659011510.npz",
#       "outputs/run_3d_T0.4328761281083057_1659011510.npz",
#       "outputs/run_3d_T0.8111308307896868_1659011510.npz",
#       "outputs/run_3d_T1.5199110829529332_1659011510.npz",
#       "outputs/run_3d_T2.848035868435799_1659011510.npz"]]

# D = [np.load(f) for f in
#      ["outputs/run_3d_T0.01_1659022107.npz",
#       "outputs/run_3d_T0.01873817422860384_1659022107.npz",
#       "outputs/run_3d_T0.03511191734215131_1659022107.npz",
#       "outputs/run_3d_T0.0657933224657568_1659022107.npz",
#       "outputs/run_3d_T0.12328467394420659_1659022107.npz",
#       "outputs/run_3d_T0.23101297000831592_1659022107.npz",
#       "outputs/run_3d_T0.4328761281083057_1659022107.npz",
#       "outputs/run_3d_T0.8111308307896868_1659022107.npz",
#       "outputs/run_3d_T1.5199110829529332_1659022107.npz",
#       "outputs/run_3d_T2.848035868435799_1659022107.npz"]]

# D = [np.load(f) for f in
#      ["outputs/run_3d_T0.01_1659029233.npz",
#       "outputs/run_3d_T0.01873817422860384_1659029233.npz",
#       "outputs/run_3d_T0.03511191734215131_1659029233.npz",
#       "outputs/run_3d_T0.0657933224657568_1659029233.npz",
#       "outputs/run_3d_T0.12328467394420659_1659029233.npz",
#       "outputs/run_3d_T0.23101297000831592_1659029233.npz",
#       "outputs/run_3d_T0.4328761281083057_1659029233.npz",
#       "outputs/run_3d_T0.8111308307896868_1659029233.npz",
#       "outputs/run_3d_T1.5199110829529332_1659029233.npz",
#       "outputs/run_3d_T2.848035868435799_1659029233.npz"]]

# D = [np.load(f) for f in
#      ["outputs/run_3d_T0.01_1659035468.npz",
#       "outputs/run_3d_T0.01873817422860384_1659035468.npz",
#       "outputs/run_3d_T0.03511191734215131_1659035468.npz",
#       "outputs/run_3d_T0.0657933224657568_1659035468.npz",
#       "outputs/run_3d_T0.12328467394420659_1659035468.npz",
#       "outputs/run_3d_T0.23101297000831592_1659035468.npz",
#       "outputs/run_3d_T0.4328761281083057_1659035468.npz",
#       "outputs/run_3d_T0.8111308307896868_1659035468.npz",
#       "outputs/run_3d_T1.5199110829529332_1659035468.npz",
#       "outputs/run_3d_T2.848035868435799_1659035468.npz",
#       "outputs/run_3d_T5.336699231206307_1659035468.npz"]]

# D = [np.load(f) for f in
#      ["outputs/run_3d_T0.01_1659044181.npz",
#       "outputs/run_3d_T0.01873817422860384_1659044181.npz",
#       "outputs/run_3d_T0.03511191734215131_1659044181.npz",
#       "outputs/run_3d_T0.0657933224657568_1659044181.npz",
#       "outputs/run_3d_T0.12328467394420659_1659044181.npz",
#       "outputs/run_3d_T0.23101297000831592_1659044181.npz",
#       "outputs/run_3d_T0.4328761281083057_1659044181.npz",
#       "outputs/run_3d_T0.8111308307896868_1659044181.npz",
#       "outputs/run_3d_T1.5199110829529332_1659044181.npz",
#       "outputs/run_3d_T2.848035868435799_1659044181.npz"]]

# D = [np.load(f) for f in
#      ["outputs/run_3d_T0.01_1659047906.npz",
#       "outputs/run_3d_T0.01873817422860384_1659047906.npz",
#       "outputs/run_3d_T0.03511191734215131_1659047906.npz",
#       "outputs/run_3d_T0.0657933224657568_1659047906.npz",
#       "outputs/run_3d_T0.12328467394420659_1659047906.npz",
#       "outputs/run_3d_T0.23101297000831592_1659047906.npz",
#       "outputs/run_3d_T0.4328761281083057_1659047906.npz",
#       "outputs/run_3d_T0.8111308307896868_1659047906.npz",
#       "outputs/run_3d_T1.5199110829529332_1659047906.npz",
#       "outputs/run_3d_T2.848035868435799_1659047906.npz"]]

# # GOOD one
D = [np.load(f) for f in
     ["outputs/run_3d_T0.01_1659053378.npz",
      "outputs/run_3d_T0.01873817422860384_1659053378.npz",
      "outputs/run_3d_T0.03511191734215131_1659053378.npz",
      "outputs/run_3d_T0.0657933224657568_1659053378.npz",
      "outputs/run_3d_T0.12328467394420659_1659053378.npz",
      "outputs/run_3d_T0.23101297000831592_1659053378.npz",
      "outputs/run_3d_T0.4328761281083057_1659053378.npz",
      "outputs/run_3d_T0.8111308307896868_1659053378.npz",
      "outputs/run_3d_T1.5199110829529332_1659053378.npz",
      "outputs/run_3d_T2.848035868435799_1659053378.npz"]]

# D = [np.load(f) for f in
#      ["outputs/run_3d_T0.01_1659059120.npz",
#       "outputs/run_3d_T0.01873817422860384_1659059120.npz",
#       "outputs/run_3d_T0.03511191734215131_1659059120.npz",
#       "outputs/run_3d_T0.0657933224657568_1659059120.npz",
#       "outputs/run_3d_T0.12328467394420659_1659059120.npz",
#       "outputs/run_3d_T0.23101297000831592_1659059120.npz",
#       "outputs/run_3d_T0.4328761281083057_1659059120.npz",
#       "outputs/run_3d_T0.8111308307896868_1659059120.npz",
#       "outputs/run_3d_T1.5199110829529332_1659059120.npz"]]

# D = [np.load(f) for f in
#      ["outputs/run_3d_T0.01_1659017667.npz",
#       "outputs/run_3d_T0.01873817422860384_1659017667.npz",
#       "outputs/run_3d_T0.03511191734215131_1659017667.npz",
#       "outputs/run_3d_T0.0657933224657568_1659017667.npz",
#       "outputs/run_3d_T0.12328467394420659_1659017667.npz",
#       "outputs/run_3d_T0.23101297000831592_1659017667.npz",
#       "outputs/run_3d_T0.4328761281083057_1659017667.npz",
#       "outputs/run_3d_T0.8111308307896868_1659017667.npz",
#       "outputs/run_3d_T1.5199110829529332_1659017667.npz",
#       "outputs/run_3d_T2.848035868435799_1659017667.npz"]]

In [299]:
sz = np.zeros(len(D))
T = np.zeros(len(D))
for n in range(len(D)):
    sz[n] = np.mean(D[n]["sz"][-50:-1])
    T[n] = D[n]["T"]

In [300]:
# C = np.loadtxt("charlie/MFGS_1D_x_prma_100.csv", delimiter=",", skiprows=1)
# C = np.loadtxt("charlie/MFGS_3D_xyz_prma_5.csv", delimiter=",", skiprows=1)
C = np.loadtxt("charlie/MFGS_3D_xyz_prma_10.csv", delimiter=",", skiprows=1)
# C = np.loadtxt("charlie/MFGS_3D_xyz_prmf_10.csv", delimiter=",", skiprows=1)
print(C.shape)

(30, 2)


In [301]:
# M = np.array([[0.01, 0.1, 1.0,], [-0.77, -0.7206, -0.5966]]).T

In [312]:
plt.figure(figsize=(5,3))
plt.semilogx(C[:,0], C[:,1], '-', color='black', linewidth=2.0, label='Charlie RC [prma]')
plt.semilogx(T, -sz, 'o', color='C0', markersize=5, label='TEMPO $\Gamma={}$'.format(D[0]['Γ'][0]))
# plt.semilogx(M[:,0],-M[:,1], 'x', color='C1', markersize=4.0, label='HEOM(lab)')
plt.axhline(0.0, linestyle='-', linewidth=1, color='gray')
plt.ylim([-0.05, 1.05])
plt.xlabel('$T$')
plt.ylabel('$s_z$')
plt.legend()
plt.tight_layout()
plt.savefig("./charlie_comp_3d.pdf")
plt.show()

In [316]:
np.savetxt('charlie_and_tempo_comp_3d.cvs', np.array([T, -sz]).T)

In [303]:
list(D[0].keys())

['α', 'ω0', 'Γ', 'dt', 'dkmax', 'epsrel', 't', 'sx', 'sy', 'sz', 'T']

In [304]:
D[0]['α'], D[0]['ω0'], D[0]['Γ'], D[0]['dt'], D[0]['dkmax'], D[0]['epsrel']

(array([10., 10., 10.]),
 array([2., 2., 2.]),
 array([0.6, 0.6, 0.6]),
 array(0.04),
 array(260),
 array(5.e-06))

In [305]:
Didx = 0
Dlidx = -50
Dridx = -1

plt.figure(figsize=(11,5))
plt.plot(D[Didx]["t"], D[Didx]["sz"], '-o', markersize=3, linewidth=1.8)
plt.axvline(D[Didx]["t"][Dlidx], linestyle='--', color='gray')
plt.axvline(D[Didx]["t"][Dridx], linestyle='--', color='gray')
plt.axvline(7.0, linestyle='-', color='black')
plt.tight_layout()
plt.xlabel("$t$")
# plt.show()
plt.savefig("tevol_test.pdf")